theme: minima
plugins:
  - jekyll-sitemap
title: Owen Allemang's homepage
description: Some random things I either discovered, thought about, or just created.

author: Owen Allemang

---
layout: page 
title: About Me
permalink: /about/
---
